FORMAT: 1A
HOST: https://maintenance-tracker-lumexralph.herokuapp.com/api/v1

# FixZit

FixZit is an api that provides users with the ability to reach out to
operations or repairs department regarding repair or maintenance requests and monitor the
status of their request.

## Starting Endpoint [/]

### Display Welcome Message [GET]

+ Response 200 (application/json)

        { 
            "message": "Welcome to FixZit, a Maintenance Tracker"
        }